import getDate from "./getDate";
// import siteCopy from "../data/copy";

// const getStaticProps = async () => {
// 	return {
// 		props: {
// 			siteCopy: siteCopy,
// 		}
// 	}
// }

const siteCopy = {
	"State/US": "State",
	"Level": "Level of Government",
	"Federal": "Federal",
	"State": "State",
	"LocalSch": "Local school district",
	"LocalOth": "Other local government",
	"\"County Name if Local\"": "County",
	"\"Authority Type\"": "Authority Type",
	"Exec directive": "Executive directive",
	"Legislation": "Legislation",
	"Opinion Ltr": "Opinion letter",
	"Regulation": "Regulation",
	"Resolution": "Resoution",
	"Other": "Other authority",
	"\"Date Intro\"": "Date",
	"6/8/2021": "June 8, 2021",
	"Summary Status": "Progress",
	"Pending": "Pending",
	"Enacted": "Approved",
	"Rejected": "Rejected",
	"Expired or Withdrawn": "Expired or withdrawn",
	// "N/A": "Issued",
	"TARGET INSTITUTION": "Target Institution",
	"K-12": "K-12",
	"Higher Ed": "Higher education",
	"Other Govt": "Other government",
	"Other Contractors": "Other contractors",
	"CONDUCT REGULATED": "Conduct Regulated",
	"Classroom teaching": "Classroom teaching",
	"Curricular content": "Curricular content",
	"Disclosure of teaching/curriculum": "Disclosure of teaching or curriculum",
	"Staff Trainings": "Staff trainings",
	"CONTENT TRIGGER": "Content Trigger",
	"\"Critical Race Theory\"": "Critical Race Theory",
	"US institns = \"inherently\" or \"fundamentally\" \"racist\"": "U.S. institutions are \"inherently\" or \"fundamentally\" \"racist\"",
	"Indiv. Respons. for systemic racism": "Individual responsible for systemic racism",
	"\"Indiv. “discomfort, guilt, anguish, or any other form of psychological distress on account of his or her race”\"": "Individual \"discomfort, guilt, anguish, or any other form of psychological distress on account of his or her race\"",
	"Meritocracy/hard work = racist": "Meritocracy or hard work is racist",
	"\"divisive concepts\"/\"controversial issues\"": "\"Divisive concepts\" or \"controvesial issues\"",
	"Bill #": "Activity Title",
	"Title/Summary": "Summary",
  "Status (link)": "See Status",
  "Full text (link)": "Read Full Text",
  "US": "Federal",
	"AL": "Alabama",
  "AK": "Alaska",
  "AS": "American Samoa",
  "AZ": "Arizona",
  "AR": "Arkansas",
  "CA": "California",
  "CO": "Colorado",
  "CT": "Connecticut",
  "DE": "Delaware",
  "DC": "District Of Columbia",
  "FM": "Federated States Of Micronesia",
  "FL": "Florida",
  "GA": "Georgia",
  "GU": "Guam",
  "HI": "Hawaii",
  "ID": "Idaho",
  "IL": "Illinois",
  "IN": "Indiana",
  "IA": "Iowa",
  "KS": "Kansas",
  "KY": "Kentucky",
  "LA": "Louisiana",
  "ME": "Maine",
  "MH": "Marshall Islands",
  "MD": "Maryland",
  "MA": "Massachusetts",
  "MI": "Michigan",
  "MN": "Minnesota",
  "MS": "Mississippi",
  "MO": "Missouri",
  "MT": "Montana",
  "NE": "Nebraska",
  "NV": "Nevada",
  "NH": "New Hampshire",
  "NJ": "New Jersey",
  "NM": "New Mexico",
  "NY": "New York",
  "NC": "North Carolina",
  "ND": "North Dakota",
  "MP": "Northern Mariana Islands",
  "OH": "Ohio",
  "OK": "Oklahoma",
  "OR": "Oregon",
  "PW": "Palau",
  "PA": "Pennsylvania",
  "PR": "Puerto Rico",
  "RI": "Rhode Island",
  "SC": "South Carolina",
  "SD": "South Dakota",
  "TN": "Tennessee",
  "TX": "Texas",
  "UT": "Utah",
  "VT": "Vermont",
  "VI": "Virgin Islands",
  "VA": "Virginia",
  "WA": "Washington",
  "WV": "West Virginia",
  "WI": "Wisconsin",
  "WY": "Wyoming"
};

export default function getText(str) {
	return siteCopy[str] || str;
}